
spring.datasource.url=jdbc:postgresql://localhost:5432/task_app
spring.datasource.username=postgres
spring.datasource.password=152587890625
spring.jpa.hibernate.ddl-auto=update
spring.thymeleaf.cache=false
server.port=8080
